POST https://localhost:7182/scheduler/
Content-Type: application/json

{
  "startAtSchedule": "2024-09-13",
  "endAtSchedule": "2024-09-15",
  "startAtWeekend": "08:00:00",
  "endAtWeekend": "11:00:00",
  "startAtWeekday": "08:00:00",
  "endAtWeekday": "13:00:00",
  "duration": 30,
  "daysOff": [
    {
      "dayOnWeek": 3
    },
    {
      "dayOnWeek": 1
    }
  ],
  "professionalId": 2
}
###
